version: '3' 
services:
  postgres:
    image: postgres:9.6
    container_name: udacity-log-analysis
    ports:
      - "5432:5432"
    network_mode: host
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=news
      - POSTGRES_USER=vagrant
      - POSTGRES_PASSWORD=
      - POSTGRES_PORT=5432
    volumes:
      - ./newsdata.sql:/docker-entrypoint-initdb.d/init.sql

