version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: udacity-postgres
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=news
      - POSTGRES_USER=vagrant
      - POSTGRES_PASSWORD=
      - POSTGRES_PORT=5432
    volumes:
      - ./newsdata.sql.gz:/docker-entrypoint-initdb.d/init.sql.gz